### ISSUE TITLE
this.configureQueue is not a function

### ISSUE THREAD

**Issue by ralemy** [impinj/itemsense-node#13]
trying to open an amqp connection gives the above error. the origin is in line 20 of this [file](https://github.com/impinj/itemsense-node/blob/1f73520194f1e830424af9e1a02b2954a5db3913/src/controllers/message-queue.controller.js).

**Comment by davidyscott** [comment]
Reza, is there a ticket for this issue in JIRA?

**Comment by seansellek** [comment]
Can you point me to the code that is throwing this error?

I believe I know what is going on here. As documented in the changelog [here](https://github.com/impinj/itemsense-node/blob/master/CHANGELOG.md#130) and the readme [here](https://github.com/impinj/itemsense-node#message-queue) the message queue behavior was moved from `itemsense.messageQueue.configure()` to the appropriate data source for which you want the queue: `itemsense.items.configureQueue()` or `itemsense.health.configureQueue()`. 

There is a bug here, in that `itemsense.messageQueue.configure()` was maintained for backwards compatibility but the plumbing behind it was stripped. I will add that back in, but any code using that method should make it's way to using `itemsense.items.configureQueue()` in the near future.

**Comment by seansellek** [comment]
Also, do you mind filing a Jira issue so we can track this?

**Comment by ralemy** [comment]
Cool. Just checked it with Greg and works perfectly. kindly push into a new npm version.

**Comment by 4141done** [comment]
Merged and version 1.4.1 pushed to npm
