### ISSUE TITLE
No CREATE/UPDATE API for items in wrapper was found

### ISSUE THREAD

**Issue by snsanich** [impinj/itemsense-node#18]
Hi.

I am looking possibility to use custom readers with itemsense solution. I found that I cannot do it through REST API.

Could you describe me a way to write items in test mode?

**Comment by ralemy** [comment]
Hi Alexander,
Nice to see you here! 
Short answer is current versions of ItemSense do not allow for simulation of readers or non-impinj reader solutions, but that is a feature down the road.

Still, please send me an email at 'ralemy at impinj dotcom' to discuss your projects and see how can I help with your RFID projects. I am a fan of your Git repos and would love to encourage you using the Impinj platform.
